import crypto from 'node:crypto';

import { SignJWT, jwtVerify } from 'jose';

import { env } from '@/lib/env';

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

export const TTL = {
  ACCESS_TTL_SEC: 60 * 60, // 1 hour
  REFRESH_TTL_SEC: 30 * 24 * 60 * 60, // 30 days
} as const;

// -----------------------------------------------------------------------------
// Access token (HS256 JWT)
// -----------------------------------------------------------------------------
//
// Claims:
//   sub        — Supabase user_id (UUID)
//   device_id  — UUIDv4 generated by the desktop on first launch
//   iat / exp  — issued at / expires at (epoch seconds)
//
// The desktop sends the access token as `Authorization: Bearer <token>` on
// every authenticated API call. proxy.ts verifies and forwards the verified
// claims to route handlers via x-uvw-user-id / x-uvw-device-id headers
// (Property P1: route handlers never trust user_id from request bodies).

export interface AccessTokenClaims {
  sub: string;
  device_id: string;
  iat: number;
  exp: number;
}

function secretKey(): Uint8Array {
  return new TextEncoder().encode(env.desktopAccessTokenSecret);
}

export async function issueAccessToken(
  userId: string,
  deviceId: string
): Promise<string> {
  return await new SignJWT({ device_id: deviceId })
    .setProtectedHeader({ alg: 'HS256' })
    .setSubject(userId)
    .setIssuedAt()
    .setExpirationTime(`${TTL.ACCESS_TTL_SEC}s`)
    .sign(secretKey());
}

export async function verifyAccessToken(
  token: string
): Promise<AccessTokenClaims | null> {
  try {
    const { payload } = await jwtVerify(token, secretKey(), {
      algorithms: ['HS256'],
    });
    if (
      typeof payload.sub !== 'string' ||
      typeof payload.device_id !== 'string' ||
      typeof payload.iat !== 'number' ||
      typeof payload.exp !== 'number'
    ) {
      return null;
    }
    return {
      sub: payload.sub,
      device_id: payload.device_id as string,
      iat: payload.iat,
      exp: payload.exp,
    };
  } catch {
    return null;
  }
}

// -----------------------------------------------------------------------------
// Refresh token (opaque, server-revocable)
// -----------------------------------------------------------------------------
//
// 32 cryptographically random bytes encoded as base64url. Stored only as
// SHA-256 hash in desktop_sessions.refresh_token_hash. The plaintext token
// lives DPAPI-encrypted on the desktop disk and is sent to the server only
// during /api/desktop/refresh and /api/desktop/signout calls.

export function newRefreshToken(): string {
  return crypto.randomBytes(32).toString('base64url');
}

// -----------------------------------------------------------------------------
// Hashing & comparison helpers
// -----------------------------------------------------------------------------

export function sha256Hex(input: string): string {
  return crypto.createHash('sha256').update(input, 'utf8').digest('hex');
}

/**
 * Constant-time string equality. Use for comparing values where timing leaks
 * would help an attacker (device_code hashes, refresh_token hashes).
 */
export function constantTimeEq(a: string, b: string): boolean {
  // timingSafeEqual requires equal-length buffers; pad shorter to match
  // longer (so we don't leak length). Different lengths still return false.
  const ab = Buffer.from(a, 'utf8');
  const bb = Buffer.from(b, 'utf8');
  if (ab.length !== bb.length) {
    // Still do a constant-time compare against itself to keep timing flat.
    crypto.timingSafeEqual(ab, ab);
    return false;
  }
  return crypto.timingSafeEqual(ab, bb);
}

// -----------------------------------------------------------------------------
// Device-code shape validation
// -----------------------------------------------------------------------------
//
// Device codes are 32 random bytes encoded as base64url, which yields a 43-
// character string (no padding). Reject anything else early so we don't burn
// a database round-trip on malformed input.

const DEVICE_CODE_RE = /^[A-Za-z0-9_-]{43}$/;
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidDeviceCode(value: unknown): value is string {
  return typeof value === 'string' && DEVICE_CODE_RE.test(value);
}

export function isValidUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value);
}
