-- Migration: 019_signups
-- Brings the `signups` table into the migration history, and closes an
-- unauthenticated write hole on it.
--
-- ---------------------------------------------------------------------------
-- WHY THIS EXISTS
--
-- `public.signups` has been live in production since before this migration
-- directory did, and NO migration ever created it — it was made by hand in the
-- dashboard. Two consequences, both found by pointing local development at a
-- fresh database for the first time:
--
--   1. A new environment has no `signups` table at all, so every landing-page
--      visit by a signed-in user logs
--        [signups/ensure] upsert error: Could not find the table 'public.signups'
--      The route is deliberately non-fatal, so nothing broke loudly and nothing
--      got recorded either.
--
--   2. The schema was only knowable by introspecting production. A table no
--      migration describes cannot be reviewed, tested against, or recreated.
--
-- The shape below was read from production's PostgREST definition, not invented:
--
--     id          bigint       not null primary key
--     name        text         not null
--     email       public.citext not null
--     created_at  timestamptz  not null default timezone('utc', now())
--     user_id     uuid         null
--
-- ---------------------------------------------------------------------------
-- WHAT THE TABLE IS FOR
--
-- A marketing/contact list: the display name and email of everyone who has ever
-- signed in, upserted by `/api/signups/ensure` (called fire-and-forget by
-- HomeClient after auth). It deliberately duplicates `auth.users.email` because
-- `auth.users` is not queryable from the client and carries no display name.
--
-- Production holds 70 rows against 97 accounts — it is a partial list, which is
-- expected for something written fire-and-forget with errors swallowed.

-- `email` is citext so that Alice@x.com and alice@x.com are the same row. Without
-- it the ON CONFLICT (email) upsert below would create a second row per casing,
-- and the marketing list would double-count people. Matching production's schema,
-- the extension lives in `public`.
create extension if not exists citext with schema public;

create table if not exists public.signups (
  -- bigint identity rather than uuid, matching production. This is a mailing
  -- list, not a security boundary, and the ids are never exposed in a URL.
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      public.citext not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  -- NULLABLE, and deliberately WITHOUT a foreign key to auth.users, because
  -- production has neither.
  --
  -- The nullability is load-bearing for the legacy static site in `__ref/`, whose
  -- sign-up form upserts a row immediately after `signUp()` — before email
  -- confirmation, so there is no session and no confirmed user to reference yet.
  --
  -- A foreign key is NOT added here even though it would be better hygiene: this
  -- migration's purpose is to make dev match prod so schema changes can be tested
  -- before they are deployed, and silently tightening the shape would defeat that.
  -- Add it in a later migration, applied to both, if wanted.
  user_id    uuid
);

-- Required by the route's `upsert(..., { onConflict: 'email' })`. Without a unique
-- index on `email`, PostgREST rejects that request outright — so this constraint
-- is not hygiene, it is what makes the endpoint work at all.
create unique index if not exists signups_email_uidx on public.signups (email);

-- Looked up by user, on the ensure path.
create index if not exists signups_user_id_idx on public.signups (user_id)
  where user_id is not null;

comment on table public.signups is
  'Marketing/contact list: display name + email of everyone who has signed in. '
  'Upserted by /api/signups/ensure. Partial by design — written fire-and-forget.';

-- -----------------------------------------------------------------------------
-- SECURITY: this table accepted writes from anyone
-- -----------------------------------------------------------------------------
--
-- Measured against production with nothing but the publishable anon key:
--
--     anon SELECT -> 401  permission denied for table signups
--     anon INSERT -> 201  row created
--
-- So the table was readable by nobody and writable by everybody. Anyone who
-- viewed the site could read the anon key out of the page and insert unlimited
-- rows — junk names, other people's email addresses, or enough volume to make the
-- list useless. Nothing rate-limits it and nothing validates it.
--
-- That grant was not gratuitous: the legacy static site in `__ref/` upserts a
-- signup row directly from the browser straight after `signUp()`, which returns no
-- session when email confirmation is on. That call can only be anonymous.
--
-- The current Next.js app does not need it. `/api/signups/ensure` calls
-- `supabase.auth.getUser()` and returns 401 before touching the table, so every
-- write it makes is authenticated.
--
-- ---------------------------------------------------------------------------
-- APPLYING THIS TO PRODUCTION IS A BEHAVIOUR CHANGE. READ FIRST.
--
-- Everything above is inert on production, which already has the table. THIS
-- section is not: it revokes a grant production is currently relying on if any
-- unauthenticated writer still exists.
--
-- Verified safe for the deployed Next.js app. NOT safe if the `__ref/` static site
-- is still served anywhere — its sign-up form would stop recording names. Confirm
-- that first; `__ref/` is a reference copy in this repo, not a deployment target.
--
-- The service role bypasses RLS entirely, so admin reads, exports and the
-- existing 70 rows are unaffected.

alter table public.signups enable row level security;

-- Anonymous callers get nothing. This is the actual fix.
revoke all on public.signups from anon;

-- Authenticated users may see the row that is theirs — matched by id OR by email,
-- because rows created by the legacy anonymous path have a null `user_id` and are
-- only identifiable by address.
drop policy if exists signups_select_own on public.signups;
create policy signups_select_own on public.signups
  for select to authenticated
  using (
    user_id = auth.uid()
    or email = (auth.jwt() ->> 'email')::public.citext
  );

-- You may create only your own row, and only claiming your own identity: both the
-- uid and the address must be yours. Without the email check a signed-in user
-- could insert rows for arbitrary addresses under their own uid.
drop policy if exists signups_insert_own on public.signups;
create policy signups_insert_own on public.signups
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and email = (auth.jwt() ->> 'email')::public.citext
  );

-- The upsert's UPDATE half. `using` accepts a pre-existing row that carries your
-- address but no uid — that is exactly the row the legacy anonymous path left
-- behind, and claiming it is the point of the ensure endpoint. `with check`
-- then forces the result to be owned by you, so a claim cannot hand the row to
-- someone else.
drop policy if exists signups_update_own on public.signups;
create policy signups_update_own on public.signups
  for update to authenticated
  using (
    user_id = auth.uid()
    or email = (auth.jwt() ->> 'email')::public.citext
  )
  with check (
    user_id = auth.uid()
    and email = (auth.jwt() ->> 'email')::public.citext
  );

-- No DELETE policy: nothing in the product deletes a signup, and a mailing-list
-- row is not the user's own data to remove here — account deletion is the path
-- for that, and it runs as the service role.

-- -----------------------------------------------------------------------------
-- VERIFY
-- -----------------------------------------------------------------------------
--   -- Anon must now be refused. With the anon key:
--   --   POST /rest/v1/signups  -> 401/403, NOT 201
--
--   -- RLS on, three policies:
--   select relrowsecurity from pg_class
--    where relname = 'signups' and relnamespace = 'public'::regnamespace;
--   -- expect: true
--   select policyname, cmd from pg_policies
--    where tablename = 'signups' order by policyname;
--   -- expect: signups_insert_own INSERT, signups_select_own SELECT,
--   --         signups_update_own UPDATE
--
--   -- Case-insensitive uniqueness really applies:
--   --   two upserts differing only in case must leave ONE row.
--
--   -- And the real flow still records a row: sign in through the app, then
--   select count(*) from public.signups;
