-- Migration: 020_reviews
-- Brings the `reviews` table into the migration history.
--
-- ---------------------------------------------------------------------------
-- WHY THIS EXISTS
--
-- Same class of gap as `signups` in migration 019: `public.reviews` has been live
-- in production since before this directory existed and NO migration created it.
-- It was made by hand in the dashboard.
--
-- Measured: production has the table and 4 rows; the fresh dev project returns
--   404 PGRST205 "Could not find the table 'public.reviews' in the schema cache"
--
-- So the review form works in production and is BROKEN in local development — you
-- cannot test it, and a new environment ships without it. That is exactly the
-- dev/prod divergence the second Supabase project was created to eliminate.
--
-- Shape read from production's PostgREST definition and cross-checked against the
-- insert in src/app/api/reviews/route.ts:
--
--     id, email, rating, review, source, created_at, user_id
--
-- ---------------------------------------------------------------------------
-- WHAT IT IS FOR
--
-- Customer reviews, submitted by signed-in users from the landing page and
-- `/feedback`. `source` distinguishes where a row came from, so testimonials on
-- the marketing page can be filtered from other inbound feedback.

create table if not exists public.reviews (
  -- bigint identity, matching `signups` and production. These ids are not exposed
  -- in URLs and this is not a security boundary.
  id         bigint generated by default as identity primary key,

  -- Denormalised from auth.users for the same reason as signups: `auth.users` is
  -- not readable from the client, and a review needs an attributable author.
  email      public.citext not null,

  -- 1..5. The route validates this range before inserting, and the constraint
  -- makes that guarantee hold for anything that bypasses the route — a rating of
  -- 0 or 11 would silently corrupt any average computed from this column.
  rating     smallint not null,

  review     text not null,

  -- Where the row came from. Defaulted so an insert that omits it is still
  -- attributable rather than null.
  source     text not null default 'review',

  -- Nullable and WITHOUT a foreign key, matching production. The route always
  -- supplies it, but a review should survive the reviewer deleting their account:
  -- a testimonial already published cannot vanish from the marketing page because
  -- a cascade fired.
  user_id    uuid,

  created_at timestamptz not null default timezone('utc'::text, now()),

  constraint reviews_rating_range check (rating between 1 and 5),
  -- Mirrors the route's `review.length < 7` rejection. Without it the table will
  -- accept the empty string, which renders as a blank testimonial.
  constraint reviews_review_not_trivial check (char_length(btrim(review)) >= 7)
);

-- The marketing page reads the newest reviews.
create index if not exists reviews_created_at_idx
  on public.reviews (created_at desc);

create index if not exists reviews_user_id_idx
  on public.reviews (user_id) where user_id is not null;

comment on table public.reviews is
  'Customer reviews submitted by signed-in users. `source` distinguishes the '
  'landing-page form from other inbound feedback.';

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
--
-- The route inserts with the CALLER'S session (`createSupabaseRouteClient`), not
-- the service role, so an insert policy is required or every submission fails.
--
-- Reviews are published content, so SELECT is open to everyone — that is the
-- point of a testimonial. Note this means the `email` column is readable by
-- anyone: it is selected by the marketing page's own query today, so this
-- documents the existing exposure rather than introducing it. If reviews are ever
-- rendered with a display name instead, narrow this to a view that omits `email`.

alter table public.reviews enable row level security;

drop policy if exists reviews_select_all on public.reviews;
create policy reviews_select_all on public.reviews
  for select using (true);

-- You may post a review only as yourself: both the uid and the address must be
-- your own. Without the email check a signed-in user could attribute a review to
-- any address they liked.
drop policy if exists reviews_insert_own on public.reviews;
create policy reviews_insert_own on public.reviews
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and email = (auth.jwt() ->> 'email')::public.citext
  );

-- No UPDATE or DELETE policy. A review is a statement of record; editing or
-- removing one is a moderation action, and moderation runs as the service role
-- rather than from the browser.

-- -----------------------------------------------------------------------------
-- VERIFY
-- -----------------------------------------------------------------------------
--   select policyname, cmd from pg_policies
--    where tablename = 'reviews' order by policyname;
--   -- expect: reviews_insert_own INSERT, reviews_select_all SELECT
--
--   -- The rating guard really applies:
--   insert into public.reviews (email, rating, review)
--     values ('x@example.com', 9, 'long enough text');   -- must FAIL
--
--   -- And submit a review through the app, then:
--   select count(*) from public.reviews;
